import type { Metadata } from "next";
import "../globals.css";
import Nav from "@/components/fragments/Nav";
import Footer from "@/components/fragments/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header className="border-b border-gray-100 bg-[#FFF9F3]">
        <Nav />
      </header>
      {children}
      {/* Footer */}
      <Footer />
    </>
  );
}
